config/routes.rb
Rails.application.routes.draw do
  root 'public#welcome'

  get 'public/welcome'
  get 'public/search'
  get 'public/status'
  get 'public/about'

  get 'public/article/:id', to: 'public#article'

  get 'api/bibliography'
  get 'api/status_counts'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  resources :articles do
    get :export, on: :member
  end
  
  resources :issues do
    get :export, on: :member
  end
  
  resources :magazines do
    get :export, on: :member
  end
end

app/models/issue.rb
class Issue < ApplicationRecord
  include Searchable

  belongs_to :magazine
  has_many :articles
  
  validates_presence_of :year

  scope :by_magazine_id, ->(id) { where(magazine_id: id) }
  scope :by_year, ->(year) { where(year: year) }

  def to_s
    "#{magazine.to_s} #{month_display} #{year} (#{sequence})"
  end

  def date_display
    "#{month_display[0..2]} #{year}"
  end

  def magazine_id_display
    magazine.to_s
  end

  def month_display
    month.blank? ? '' : Date::MONTHNAMES[month]
  end

  def self.month_collection
    collection = []
    Date::MONTHNAMES.each_with_index { |m, i| collection << [m, i] unless m.nil? }
    collection
  end

  def friendly_name
    return special if special.present?

    I18n.t(
      "issue.friendly_name.#{magazine.slug}",
      volume: volume,
      number: number,
      sequence: sequence,
      month_name: month.present? ? Date::MONTHNAMES[month] : '',
      year: year
    ).squeeze(' ')
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  load_and_authorize_resource

  def index
    sort = params[:sort] || :id
    direction = params[:direction] || :asc

    @issues = Issue.accessible_by(current_ability)
                   .eager_load(:magazine)
                   .search(params.slice(:by_magazine_id, :by_year))
    @full_count = @issues.count

    # @issues = @issues.order(sort => direction)
    #                  .page(params[:page])
    @issues = @issues.page(params[:page])
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)

    if @issue.save
      redirect_to @issue
    else
      render 'new'
    end
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])

    if @issue.update(issue_params)
      redirect_to @issue
    else
      render 'edit'
    end
  end

  private

  def issue_params
    params.require(:issue).permit(:magazine_id,
                                  :year,
                                  :month,
                                  :volume,
                                  :number,
                                  :sequence,
                                  :special)
  end
end

app/helpers/issue_helper.rb
module IssueHelper
  def archive_base_url(issue)
    # useless local variables for readability:
    my_slug = issue.magazine.slug
    my_suffix = issue.magazine.archive_suffix.to_s

    "cbm_magazine_index-#{my_slug}#{my_suffix}/#{my_slug}"
  end

  def archive_slug(issue)
    # useless local variables for readability:
    my_slug = issue.magazine.slug
    my_sequence = issue.special_slug || ('%02i' % issue.sequence)
    my_month = issue.month.blank? ? '' : ('%02i' % issue.month)

    "#{issue.year}/#{my_slug}-#{my_sequence}-#{issue.year}#{my_month}"
  end

  def article_page(page)
    "page/#{page}/mode/2-up"
  end

  def archive_download_link(issue)
    "https://archive.org/download/#{archive_base_url(issue)}/#{archive_slug(issue)}.pdf"
  end

  def archive_jpeg_link(issue)
    "https://archive.org/download/#{archive_base_url(issue)}/#{archive_slug(issue)}_jp2.zip"
  end

  def archive_ocr_link(issue)
    "https://archive.org/stream/#{archive_base_url(issue)}/#{archive_slug(issue)}_djvu.txt"
  end

  def archive_view_issue_link(issue)
    "https://archive.org/details/#{archive_base_url(issue)}/#{archive_slug(issue)}?view=theater"
  end

  def archive_view_article_link(issue, page)
    "https://archive.org/details/#{archive_base_url(issue)}/#{archive_slug(issue)}/#{article_page(page)}"
  end

  def cover_image_url(issue)
    if issue.special_slug
      "covers/#{issue.magazine.slug}/#{issue.magazine.slug}-#{issue.special_slug}.jpg"
    else
      "covers/#{issue.magazine.slug}/#{issue.magazine.slug}-#{'%02i' % issue.sequence}.jpg"
    end
  end
end

app/views/issues/_form.html.erb
<%= simple_form_for @issue, html: { class: 'input-form' } do |f| %>
  <div class="validation-errors">
    <%= render partial: 'alerts/validation_errors', locals: { f: f } %>
  </div>

  <div class="input-fields">
    <fieldset>
      <legend><%= I18n.t('issue.fieldset.metadata') %></legend>
      <%= f.association :magazine,
                        as: :select, 
                        collection: Magazine.all,
                        required: true,
                        prompt: I18n.t('select.magazine') %>
      <%= f.input :year,
                  as: :select,
                  collection: Rails.configuration.first_year..Rails.configuration.last_year,
                  required: true,
                  prompt: I18n.t('select.year') %>
      <%= f.input :month,
                  as: :select,
                  collection: Issue.month_collection,
                  required: false,
                  prompt: I18n.t('select.month') %>
      <%= f.input :volume, as: :integer %>
      <%= f.input :number, as: :integer %>
    </fieldset>
  </div>
  
  <div>
    <%= f.button :submit unless action_name == 'show' %>
  </div>
<% end %>

app/views/issues/_index_table.html.erb
<div id="index-table">

  <table class="index-table table-striped">
    <tr class="issue-index-row">
      <%#= sortable 'name' %>
      <%#= sortable 'owner_id' %>
      <%#= sortable 'min_vnum' %>
      <th>Magazine</th>
      <th>Date</th>
      <th>Volume</th>
      <th>Issue Number</th>
      <th class="action"></th>
      <%= tag.th class: 'action' if can? :update, Issue %>
      <%#= tag.th class: 'action' if can? :export, Issue %>
      <%#= tag.th class: 'action' if can? :destroy, Issue %>
    </tr>

    <% @issues.each do |issue| %>
      <tr class="issue-index-row">
        <td><%= issue.magazine %></td>
        <td><%= issue.date_display %></td>
        <td><%= "Vol. #{issue.volume}, No. #{issue.number}" unless issue.number.blank? %></td>
        <td><%= issue.sequence %></td>
        <td class="action">
          <%= link_to svg('view'),
                      issue_path(issue),
                      title: I18n.t('index_table.view') %>
        </td>
        <% if can? :update, Issue %>
          <%= tag.td class: 'action' do %>
            <%= link_to svg('edit'),
                        edit_issue_path(issue),
                        title: I18n.t('index_table.edit') %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>

  <%= paginate @issues %>
</div>

app/views/issues/_search.html.erb
<%= form_tag issues_path, method: 'get', class: 'search-form' do %>
  <fieldset>
    <legend>
      <span><%= I18n.t('search.title') %></span>
    </legend>
    <div class="search-field-top">
      <label><%= I18n.t('search.by_magazine_id') %></label>
      <%= select_tag :by_magazine_id,
                     options_for_select(Magazine.collection, params[:by_magazine_id]),
                     prompt: I18n.t('select.magazine'),
                     class: 'search-select' %>
    </div>
    <div class="search-field">
      <label><%= I18n.t('search.by_year') %></label>
      <%= select_tag :by_year,
                     options_for_select((Rails.configuration.first_year..Rails.configuration.last_year), params[:by_year]),
                     prompt: I18n.t('select.year'),
                     class: 'search-select' %>
      
    </div>
    <div class="search-buttons">
      <%= submit_tag I18n.t('button.search.submit'), name: nil, class: 'btn btn-default' %>
      <%= link_to I18n.t('button.search.clear'), issues_path, class: 'btn btn-clear' %>
    </div>
  </fieldset>
<% end %>

app/views/issues/index.html.erb
<% content_for :title do %>
  <%= I18n.t('page.action_title.index', model: 'Issues') %>
  <%= link_to svg('new'), new_issue_path, title: I18n.t('index_table.create'), class: 'icon' %>
<% end %>
  
<div class="index-page">
  <div class="pagination-info">
    <%= pagination_info(page: params[:page], page_count: @issues.count, full_count: @full_count) %>
  </div>

  <div></div>

  <div>
    <%= render 'index_table' %>
  </div>

  <div>
    <%= render 'search' %>
  </div>
</div>

app/views/issues/show.html.erb
<% content_for :title do %>
  <%= I18n.t('page.action_title.show', record: @issue.to_s) %>
  <%= link_to svg('edit'), edit_issue_path(@issue), title: I18n.t('index_table.edit'), class: 'icon' %>
  <%= link_to svg('new'), new_issue_path, title: I18n.t('index_table.create'), class: 'icon' %>  
<% end %>

<%= render 'form' %>