config/routes.rb
Rails.application.routes.draw do
  root 'public#welcome'

  get 'public/welcome'
  get 'public/search'
  get 'public/status'
  get 'public/about'

  get 'public/article/:id', to: 'public#article'

  get 'api/bibliography'
  get 'api/status_counts'

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }

  resources :articles do
    get :export, on: :member
  end
  
  resources :issues do
    get :export, on: :member
  end
  
  resources :magazines do
    get :export, on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commodore 8-Bit Magazine Index</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <header>
      <div class="header-left">
      <%= link_to (user_signed_in? ? public_welcome_path : root_path) do %>
        <%= image_tag('cbmmag_logo.png', alt: 'CBM Magazine Index', class: 'cbm-logo') %>
      <% end %>
      </div>
      <div class="header-right">
        <nav class="nav-menu" id="public-nav">
          <%= link_to 'Home', public_welcome_path, data: { turbolinks: false } %>|
          <%= link_to 'Search', public_search_path, data: { turbolinks: false } %>|
          <%= link_to 'Status', public_status_path %>|
          <%= link_to 'About', public_about_path %>
        </nav>
      </div>
    </header>

    <div class="bar-red"></div>
    <div class="bar-orange"></div>
    <div class="bar-yellow"></div>
    <div class="bar-green"></div>
    <div class="bar-blue"></div>

    <% if user_signed_in? %>
      <nav id="top-nav">
        <%= link_to 'Articles', articles_path, class: 'navbar-link' %>&nbsp;|
        <%= link_to 'Issues', issues_path, class: 'navbar-link' %>&nbsp;|
        <%= link_to 'Magazines', magazines_path, class: 'navbar-link' %>
        <div class="logout-link">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link' %>
        </div>
      </nav>
    <% end %>    

    <section id="title-bar">
      <div id="title-content">
        <% if yield(:title).present? %>
          <h1 id="page-title"><%= yield(:title) %></h1>
        <% end %>
      </div>
    </section>

    <%= yield %>

    <footer>
      <%= tag.span do %>
        Commodore 8-Bit Magazine Index &ndash; Copyright &copy; <%= Time.now.year %> Myles L. Skinner &ndash; All Rights Reserved.
      <% end %>
      <% unless user_signed_in? %>
        <span class="admin-login">
          <%= link_to 'Admin Login', new_session_path('user'), class: 'navbar-link' %>
        </span>
      <% end %>
    </footer>
  </body>
</html>